### ISSUE TITLE
Make the CommandAPI shade-able

### ISSUE THREAD

**Issue by JorelAli** [JorelAli/CommandAPI#133]
**Please describe your suggestion**
Make the CommandAPI in such a way you can shove it in another plugin

**Proposal**
We make the CommandAPI shade-able. This will consist of two user-facing methods:

```
CommandAPI.onLoad()
CommandAPI.onEnable()
```

These methods are to be placed at the top of the target's `onLoad()` and `onEnable()` method.

**Other things that need to be done to make this work:**

- We make a maven module specifically for shading. It's an extension of `commandapi-output` but without all of the plugin.yml, config.yml and all that stuff.
- I don't actually know what code you need to add to maven or gradle to shade things, so either myself or someone else can contribute that information so I can put it in the documentation!

People who may be interested and are definitely worth notifying: 
- @Draycia

**Comment by Draycia** [comment]
You could also have the default behaviour not output a usable plugin, and then have the module `commandapi-plugin` output a usable plugin that provides CommandAPI. 

This way, both people who shade it and those who don't will use the same dependency, the difference being the extra stuff to shade. 

Will reduce the amount of docs / confusion, in my opinion.

**Comment by JorelAli** [comment]
So I have 3 main modules:
- `commandapi-core` which is the plain ol' API*
- `commandapi-output` which is the plugin
- `commandapi-shade` which is for shading

*Except of course the fact that `commandapi-core` is a fully useable plugin with the major downside of it doesn't work _(because it's not the main plugin output)_.

Hopefully it doesn't cause confusion, but I should probably be a bit more open about the maven modules in the documentation so everyone knows what's actually going on

**Comment by JorelAli** [comment]
Implemented in 10ebaeea8a6059f04bc31a79fecd706bd5f0d2ef. Shading will be accessible in the 4.1 release.
