### ISSUE TITLE
(Using shading feature) Whether to disable debug/verbose messages completely

### ISSUE THREAD

**Issue by jho5245** [JorelAli/CommandAPI#143]
**Please describe your suggestion**
I used Converter.convert(plugin) to register all plugin commands. If there are so many plugins, and my plugin enables, it shows too many messages for registering. even when CommandAPI.onLoad(false);

**Comment by JorelAli** [comment]
https://github.com/JorelAli/CommandAPI/projects/11
Reducing verbosity has already been noted and is present in v5.0's TODO list! Thanks for the issue, I'll make sure to mark this as resolved when it's done and I'll ensure that debug messages (if any) are way less verbose 😄

**Comment by JorelAli** [comment]
Commit d16750edb28c1bc9a586927daa7f603fafcbb8d4 ensures that `verbose: false` and `CommandAPI.onLoad(false)` actually work and ensures that everything is quieter now.

Now only the following messages will be displayed (regardless of verbose setting):
- Whether it hooked into the NBTAPI or Spigot
- The number of permissions that were links for permission linkage
- When it reloads datapacks
