### ISSUE TITLE
404 link for simple literal argument (missing page?) also doesn't show up in search

### ISSUE THREAD

**Issue by SpaceCheetah** [JorelAli/CommandAPI#144]
Chapter 8.11.1 in the developer's note, line 190 in https://github.com/JorelAli/CommandAPI/blob/master/docs/4.3/literalarguments.html line 190

It says "The LiteralArgument class is now obsolete! If you want to implement literals easily, consider using the much more intuitive SimpleLiteralArgument, which is described in more detail here!", with here being a link to [https://www.jorel.dev/CommandAPI/4.3/simplelitargs.html](url). That link goes to a 404, and searching the documentation does not show the page.

**Proposed fix**
Looking through the documentation folder, it appears that this page simply doesn't exist. Looking through version 4.3, I don't see a SimpleLiteralArgument class, nor any other reference to such. Is this a future feature that got into the documentation by accident, or something else? Either way, for now that developer's note should simply be removed.

**Comment by SpaceCheetah** [comment]
Looking more closely, it appears this might be an older name or something for MultiLiteralArgument?

**Comment by JorelAli** [comment]
Ah yes, that was indeed the old name for the MultiliteralArgument. I'll make sure to fix that on the live website as soon as I can 😃
