### ISSUE TITLE
Add withPermission(String) to Arguments

### ISSUE THREAD

**Issue by 469512345** [JorelAli/CommandAPI#149]
**Please describe your suggestion**
A clear and concise description of what the suggestion is.

Please add withPermission(String) to the Argument class. Every single time I use withPermission in my code, I have to include CommandPermission.fromString() as well, which is just very verbose. Having a convenience method in the Argument class that quietly does this conversion for me would make my code much more readable

**Please supply examples of the desired inputs and outputs**
`arguments.add(new PlayerArgument("player").withPermission(CommandPermission.fromString(Perm.MAXHEALTH_OTHER)));`
would become
`arguments.add(new PlayerArgument("player").withPermission(Perm.MAXHEALTH_OTHER));`
which is much more readable and contains only the useful code.

Just want something like this in Argument class
`
public final Argument withPermission(String permissionString) {
	return this.withPermission(CommandPermission.fromString(permissionString));
}
`

**Comment by JorelAli** [comment]
Sure thing, can do 👍

**Comment by 469512345** [comment]
Is there a good justification as to why CommandPermission is used at all over a String to represent permissions?

**Comment by JorelAli** [comment]
Yes, there isn't an existing permission node that represents "being an operator (op)" and there's also no permission node that represents "nothing" (i.e. requiring no permission to run a command).

**Comment by JorelAli** [comment]
Implemented in 37d21de, scheduled for 5.1 release.

**Comment by JorelAli** [comment]
@469512345 Version 5.1 of the CommandAPI has been released.
