### ISSUE TITLE
A way to enforce that an argument provided by a user is actually a suggestion

### ISSUE THREAD

**Issue by JorelAli** [JorelAli/CommandAPI#168]
**Please describe your suggestion**
Things like custom arguments primarily depend on their suggestions. These suggestions are merely "suggestions" - users can enter whatever they want, which can typically lead to unintended side-effects. It's effort for developers to have to manually check if an input is something from a suggestion or not.

Perhaps have some sort of generic message `'input' is not a valid input for this command`, and have something like `CommandAPICommand.suggestionsOnly()`

**Comment by JorelAli** [comment]
This is technically infeasible. Due to the new suggestion system, suggestions can be changed whilst a player is typing and thus produce different results based on what has been partially typed. As such, it's impossible to enforce if an argument is actually a suggestion or not.

**Comment by Minenash** [comment]
Another way you could implement this dev-side is have something like `.limitTo(List)` or `.limitValues(List)`

**Comment by JorelAli** [comment]
Possibly, but at that point it's easier implementing that in your main command body

**Comment by Minenash** [comment]
Oh it was only for successful/failed command, not any visual stuff (like red input)

**Comment by JorelAli** [comment]
Yup.
