### ISSUE TITLE
[Documentation Suggestion] Mention the namespace commands are registered under

### ISSUE THREAD

**Issue by jvdoorn** [JorelAli/CommandAPI#173]
**Proposal**
On the Discord it was mentioned that all the commands registered via CommandAPI are registered on the the `minecraft:` namespace. I think it would be good to add that to the Wiki.

**Comment by JorelAli** [comment]
Implemented in [release 6.2.0](https://github.com/JorelAli/CommandAPI/releases/tag/6.2.0).
