### ISSUE TITLE
not working in 1.16.5

### ISSUE THREAD

**Issue by JoBo216** [JorelAli/CommandAPI#187]
version 4.2

**Minecraft version**
1.16.5

**Describe the bug**
the consol tell that the version 1.16.5 is not supported.

**Expected behavior**
an update that run on 1.16.5

![Bild_2021-02-12_180225](https://user-images.githubusercontent.com/78974579/107798466-76a6e500-6d5c-11eb-9686-35eaa2125a7a.png)
![Bild_2021-02-12_180258](https://user-images.githubusercontent.com/78974579/107798510-8a524b80-6d5c-11eb-9bfc-ad7535b1ac0e.png)

**Additional context**
https://pastebin.com/7TbnMngs

**Comment by JorelAli** [comment]
Minecraft 1.16.5 support was introduced in CommandAPI v5.7 and onwards.

**Comment by JorelAli** [comment]
The solution is to update your version of the CommandAPI. Marking as closed.
