### ISSUE TITLE
Custom command executor

### ISSUE THREAD

**Issue by TomasWeg** [JorelAli/CommandAPI#191]
I suggest add a way to create custom command executors, for example, for custom created CommandSender, such as a custom player object

**Comment by JorelAli** [comment]
How do you imagine the syntax for this would look like, and how does it differ to say...

```java
new CommandAPICommand("mycommand")
  .executes((sender, args) -> {
    CustomPlayer customPlayer = CustomPlayer.of(sender);
  })
  .register();
```

**Comment by TomasWeg** [comment]
The .of method just casts?

**Comment by JorelAli** [comment]
You've stated that you have a custom player object, surely you must have some logic to construct a custom player object from a CommandSender or Player object, I'm just providing an example, such as `new CustomPlayer(sender);`

**Comment by TomasWeg** [comment]
Yeah, i know. But my point is to avoid writing CustomPlayer.of(sender) everytime I write a command.

**Comment by JorelAli** [comment]
You're asking me to add this very specific feature to an API which is only really specific to your scenario, so you can write 23 characters less code for every command.

**Comment by zoltus** [comment]
Cant you just make new class and extend commandapicommand and do ur own stuff there?

**Comment by JorelAli** [comment]
@TomasWeg The optimal solution is to simply extend the `CommandAPICommand` class:

```java
import java.util.function.BiConsumer;
import dev.jorel.commandapi.CommandAPICommand;

public class CCommandAPICommand extends CommandAPICommand {

	public CCommandAPICommand(String commandName) {
		super(commandName);
	}
	
	public CCommandAPICommand executesCustom(BiConsumer<CustomPlayer, Object[]> executor) {
		super.executes((sender, args) -> {
			executor.accept(CustomPlayer.of(sender), args);
		});
		return this;
	}

}
```

That way, you can then use:
```java
new CCommandAPICommand("mycommand")
    .executesCustom((custPlayer, args) -> {
        //code
    })
    .register();
```

**Comment by JorelAli** [comment]
Closing this issue. A solution has been provided which achieves the goals set out by this issue.
