### ISSUE TITLE
The maven repository branch is not supporting dependabot.

### ISSUE THREAD

**Issue by portlek** [JorelAli/CommandAPI#203]
**Describe the bug**
The dependabot can't get version from the mvn-repo branch so It can't check for the new versions.

I recommend you to use at least jitpack.io

**Comment by JorelAli** [comment]
As you can imagine, I have no experience with jitpack.io. By any chance would you know how to get it to install the Spigot libraries (which can only be gained using BuildTools) which are required by the CommandAPI?

**Comment by portlek** [comment]
> As you can imagine, I have no experience with jitpack.io. By any chance would you know how to get it to install the Spigot libraries (which can only be gained using BuildTools) which are required by the CommandAPI?

CodeMc's nms repository.

**Comment by portlek** [comment]
Or simply you can use GitHub Actions with BuildTools and, deploy to maven central. There are 2 way to do that actually.

**Comment by portlek** [comment]
Here is the CodeMc's nms repository:

https://repo.codemc.org/repository/nms/

These are the versions:

https://repo.codemc.io/service/rest/repository/browse/nms/org/spigotmc/spigot/

**Comment by portlek** [comment]
![offer](https://user-images.githubusercontent.com/12835420/118375500-adde9980-b5ca-11eb-8e48-e5e71a4e5e09.png)

**Comment by JorelAli** [comment]
Frankly, this is a trade offer I cannot refuse. I've added a `jitpack.yml` file and a `jitpacksetup.sh` script to pull from CodeMc's NMS repo _(May need tweaking, expect who knows how long until it works)_. If this does work, I'll definitely use jitpack going forwards as opposed to my mvn-repo branch

**Comment by portlek** [comment]
Alright, thanks. I'll test it ASAP.

**Comment by portlek** [comment]
As jitpack's log says, maven can't find the NMS dependencies.
![image](https://user-images.githubusercontent.com/12835420/118375782-9accc900-b5cc-11eb-9d8d-bb6d31634ede.png)

I'll try a simple solution for that.

**Comment by JorelAli** [comment]
```
Running before_install command:
./jitpacksetup.sh
/script/buildit.sh: line 41: ./jitpacksetup.sh: Permission denied
```
This doesn't look good.

**Comment by portlek** [comment]
> ```
> Running before_install command:
> ./jitpacksetup.sh
> /script/buildit.sh: line 41: ./jitpacksetup.sh: Permission denied
> ```
> 
> This doesn't look good. (Build log: https://jitpack.io/com/github/JorelAli/CommandAPI/-6f0a202df0-1/build.log)

Oh, I guess It needs `chmod +x ./jitpacksetup.sh`.

**Comment by JorelAli** [comment]
Right, the latest commit _should_ do it?

**Comment by portlek** [comment]
No, you should add it in to here
![image](https://user-images.githubusercontent.com/12835420/118377444-f485c100-b5d5-11eb-8c0f-75bceda22df8.png)

**Comment by JorelAli** [comment]
```bash
./jitpacksetup.sh
Installing Spigot libraries...
./jitpacksetup.sh: 3: ./jitpacksetup.sh: Syntax error: "(" unexpected
Going into directory: ./CommandAPI
```
Uuugh, we have bash nonsense!
It appears the script is being executed, but just not working

**Comment by portlek** [comment]
Btw, why you don't simply use CodeMc's nms repository on the pom.xml as a real repository?
example:
![image](https://user-images.githubusercontent.com/12835420/118377506-4b8b9600-b5d6-11eb-93fa-83ab3530cd21.png)

**Comment by JorelAli** [comment]
If I do that, I'd have to rebuild every previous version of the CommandAPI. Instead, it's much easier to tell jitpack to just install them in the repo

**Comment by portlek** [comment]
![image](https://user-images.githubusercontent.com/12835420/118377868-95757b80-b5d8-11eb-9feb-f9910e982287.png)
This is weird because I couldn't find the method too. But your repository built for 1.16.4/5. The CraftSound class which changed last year is not longer an enum class, and It has not the sound type fields.

**Comment by JorelAli** [comment]
Oh yeah... so for some bizarre reason, the CommandAPI's annotation preprocessor doesn't work on CI, but I've never been able to reproduce this on my local machine.
https://jitpack.io/com/github/JorelAli/CommandAPI/7c1ebd8844/build.log
```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] Field: String CraftSound.minecraftKey does not exist
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for commandapi 5.11:
[INFO] 
[INFO] commandapi ......................................... SUCCESS [  3.837 s]
[INFO] commandapi-preprocessor ............................ SUCCESS [  2.081 s]
[INFO] commandapi-core .................................... SUCCESS [01:15 min]
[INFO] commandapi-1.16.4 .................................. FAILURE [  0.911 s]
[INFO] commandapi-1.16.2 .................................. SKIPPED
[INFO] commandapi-1.16.1 .................................. SKIPPED
[INFO] commandapi-1.15 .................................... SKIPPED
[INFO] commandapi-1.14.4 .................................. SKIPPED
[INFO] commandapi-1.14.3 .................................. SKIPPED
[INFO] commandapi-1.14 .................................... SKIPPED
[INFO] commandapi-1.13 .................................... SKIPPED
[INFO] commandapi-1.13.1 .................................. SKIPPED
[INFO] commandapi-1.13.2 .................................. SKIPPED
[INFO] commandapi-vh ...................................... SKIPPED
[INFO] commandapi-plugin .................................. SKIPPED
[INFO] commandapi-shade ................................... SKIPPED
[INFO] commandapi-annotations ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:22 min
[INFO] Finished at: 2021-05-15T20:51:19Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project commandapi-1.16.4: Compilation failure
[ERROR] Field: String CraftSound.minecraftKey does not exist
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :commandapi-1.16.4
Build tool exit code: 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
Found artifact: dev.jorel:commandapi:5.11
2021-05-15T20:51:22.822348502Z
Exit code: 0
```

**Comment by JorelAli** [comment]
Wait what

> This is weird because I couldn't find the method too. But your repository built for 1.16.4/5. The CraftSound class which changed last year is not longer an enum class, and It has not the sound type fields.

Wait what, there's a different CraftSound class? This is the first time I'm heading of this...

**Comment by portlek** [comment]
> Wait what
> 
> > This is weird because I couldn't find the method too. But your repository built for 1.16.4/5. The CraftSound class which changed last year is not longer an enum class, and It has not the sound type fields.
> 
> Wait what, there's a different CraftSound class? This is the first time I'm heading of this...

Yes there is a CraftSound class but look at this commit on spigot

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/424598d2943c6d787dafcfd60251fe9fadcc9d70#src/main/java/org/bukkit/craftbukkit/CraftSound.java#201

**Comment by portlek** [comment]
They changed the enum class into a normal class and removed fields + getSound(String) method.

**Comment by JorelAli** [comment]
Right, I figured out what's going on now.
Minecraft 1.16.4 has the old sound stuff but Minecraft 1.16.5 has the new sound stuff AND it all has the same package number `org.bukkit.craftbukkit.v1_16_R3`...

**Comment by portlek** [comment]
> Right, I figured out what's going on now.
> Minecraft 1.16.4 has the old sound stuff but Minecraft 1.16.5 has the new sound stuff AND it all has the same package number `org.bukkit.craftbukkit.v1_16_R3`...

Yea both 1.16.4 and 1.16.5 have the same package name.

**Comment by JorelAli** [comment]
Ugh, that's such a pain. Why does it have to be like this...

**Comment by portlek** [comment]
> Ugh, that's such a pain. Why does it have to be like this...

NMS and CraftBukkit coders learnt versioning stuffs at a wrong place :D

**Comment by JorelAli** [comment]
Right, let me try and make a new release 5.12 which should fix that annotation message hopefully?

**Comment by portlek** [comment]
Alright. Btw Minecraft will use Java 16 in the next realease which is 1.17 and, I guess we have some reflection restrictions after Java 15. So, I guess your reflection stuffs may not work.

**Comment by JorelAli** [comment]
Have you considered joining our Discord?
