### ISSUE TITLE
CommandAPI shadows de.tr7zw.nbtapi without prefixing it

### ISSUE THREAD

**Issue by toddharrison** [JorelAli/CommandAPI#225]
**CommandAPI version:** 6.0.5

**Minecraft version:** 1.17

**What I did:**

When starting CommandAPI and Staff++ at the same time, I get this error:
[21:16:36 WARN]: [CommandAPI] Loaded class de.tr7zw.nbtapi.NBTContainer from StaffPlus v1.17.4 which is not a depend, softdepend or loadbefore of this plugin.
This indicates that both Staff++ and CommandAPI are shadowing the nbtapi library without prefixing it to prevent overloading. Both libraries should prefix the shadowed library in case they require different versions.

**Actual result:**

```
see above
```

**What should have happened:**

see above

**Comment by JorelAli** [comment]
The CommandAPI does not shade the NBTAPI - it only depends on the NBTAPI plugin. If you use the CommandAPI and the NBTAPI separately (both in plugin form with no shading), it should work normally.
See also issue #223.

**Comment by toddharrison** [comment]
Thanks, this seems to work. I believe that Staff++ may be shading it, but adding the plugin removed the error message. Thank you!
