### ISSUE TITLE
Customizable messages

### ISSUE THREAD

**Issue by MatsG23** [JorelAli/CommandAPI#229]
Hello!

I have a suggestion. Why can't we edit the messages that come from the API itself, like this one:

<img width="951" alt="Screenshot 2021-07-12 190141" src="https://user-images.githubusercontent.com/60609373/125327730-b7268100-e343-11eb-9e9a-2c1b6044a204.png">

**This would allow localization and the possibility to simplify the messages**

Best Regards
MatsG23

**Comment by JorelAli** [comment]
Nice idea, I like it. I'll try to implement this in the next release.

**Comment by yngvkie** [comment]
I don't want to rush anything, but how does the situation progress? About when can we expect a new release? The players on my server are quite young and need to get more personalized messages.

**Comment by JorelAli** [comment]
@yngvkie The situation is that I've currently been on holiday this whole week!
I'll try to schedule a release with this feature for Wednesday at the latest, tomorrow at the earliest.

**Comment by JorelAli** [comment]
@yngvkie So I did say Wednesday at the latest and unfortunately there have been some unexpected delays (mostly covid related, ended up having to unexpectedly go into self isolation).
The main code itself is actually done, all that needs doing before a release is writing up the changes to the wiki and running one quick test to ensure everything's working as intended.
I hope to release very soon, apologies for the delay!

**Comment by yngvkie** [comment]
Okay, great. Will it also be possible to change the message, for example from this gif [Link](https://github.com/JorelAli/CommandAPI/blob/master/images/printnumber.gif). I mean here `Integer must not be less than...`. I'm not entirely sure how it works. Are these messages 100% client-side?

**Comment by JorelAli** [comment]
@yngvkie Unfortunately, those messages are hardcoded into the Minecraft client. It may be possible to change these by providing a server resourcepack which changes these messages, but I've personally never tried that and can't give any more information about whether it is a solution that works.

**Comment by JorelAli** [comment]
Implemented in [release 6.2.0](https://github.com/JorelAli/CommandAPI/releases/tag/6.2.0).
