### ISSUE TITLE
The annotation system should protect against missing annotations on parameters

### ISSUE THREAD

**Issue by Steel-Dev** [JorelAli/CommandAPI#233]
**CommandAPI version:** _6.1.0_

**Minecraft version:** _1.16.5 & 1.17.1 (devving a plugin for both versions)_

**What I did:**

- Shaded the API
- Added the annotation system as well
- Made a command with sub-commands using the annotation system
- Package jar

**Actual result:**

gives `java: reached end of file while parsing` error upon packaging because auto-generated command file isn't being fully generated.

Auto generated file (that I cannot edit):
![image](https://user-images.githubusercontent.com/12509016/127244397-9a437e53-8152-4fdc-aebd-8f5631c6169c.png)

My actual command file:
![image](https://user-images.githubusercontent.com/12509016/127244497-a46f7ec0-d2fa-4b35-8213-d401946776ee.png)

**What should have happened:**

- The auto-generated command file should have well.. generated completed.

**Comment by Steel-Dev** [comment]
Update: issue resolved but was told to keep issue open by the developer on discord so he can improve the annotations.

**Comment by JorelAli** [comment]
This was apparently fixed in 40e8304dac4b3beb4cb54412b9fec5c6bcdebaf6, which bizarrely is before the time that this issue was raised. In practice, when other parameters without annotations are present, compilation will fail.
