### ISSUE TITLE
inputInfo in CustomArgument causes compile error on JDK 16.0.2

### ISSUE THREAD

**Issue by R3charged** [JorelAli/CommandAPI#240]
**CommandAPI version:** _6.3.0_

**What I did:**
I made a CustomArgument. When compiling it spits an error.

```
Stuff that happened when I did it (post error logs here for example)
```
:18:24
java: cannot access java.lang.Record
  class file for java.lang.Record not found

**Note**

I'm only a sophomore CS major so I don't know much about the nitty-gritty. From what I've searched online, it says Record cannot be extended and CustomArgumentInfo extends Record? ¯\_(ツ)_/¯

**Comment by JorelAli** [comment]
Hi!
I wasn't able to find any issues with compiling using CustomArguments. Since you haven't posted any code that you tried, there's not much that I can really offer to help as I don't know the full state of your setup.

Have you tried following the documentation's example for using a `CustomArgument`? I can confirm that this works!
https://commandapi.jorel.dev/6.3.0/customarguments.html#example---world-argument

**Comment by R3charged** [comment]
My bad, here's a screenshot of the setup. Even the example code throws this error. I'm using intellij at language level 16, if that helps at all.
![Screenshot 2021-08-21 185932](https://user-images.githubusercontent.com/56638676/130336845-c17da619-15c8-4b59-89e0-cd4af0c2db2d.png)

**Comment by JorelAli** [comment]
It appears you're not compiling using Java 16. While you may have Java 16 installed on your computer, IntelliJ needs to know to use Java 16 for compilation. I'm not too familiar with IntelliJ (especially not from memory!), hopefully this helps?
https://blog.jetbrains.com/idea/2021/03/java-16-and-intellij-idea/#:~:text=IntelliJ%20IDEA%20Configuration&text=You%20can%20configure%20it%20to,16%20directly%20from%20IntelliJ%20IDEA.

**Comment by R3charged** [comment]
Hmm, I've tried compiling it with JDK 16.0.2 and 16.0.1 and I tried changing the language level to 16(Preview) like the intellij blog post instructed but with no change in the results :(. I also checked java -version, and it's using 16.0.2

**Comment by JorelAli** [comment]
How are you compiling your project? Are you using a package manager such as Maven or Gradle? If so, you may have to explicitly declare that you want to use Java 16 in the build script.

Another idea may be to add your JDK path to the `JAVA_HOME` environment variable (see the following link on how to do this if you are unsure: https://www.baeldung.com/java-home-on-windows-7-8-10-mac-os-x-linux )

**Comment by R3charged** [comment]
I figured it out. I did have my language level for the PROJECT set to 16, but for the MODULE, it was set to 8. Changing the module language level to 16 made it work.
Thanks for the help JorelAli, probably wouldn't have figured this out if I didn't have to check whether I started this as a Gradle project or not. <3
