### ISSUE TITLE
Permissions dont work when shading

### ISSUE THREAD

**Issue by Zoltus** [JorelAli/CommandAPI#245]
**CommandAPI version:** 6.3.1

**Minecraft version:** 1.17

When shading commandapi, i couldnt get the permissions to work. It just says no permissions.
I created clean server with clean plugin which had only one command.

Permissions works if the plugin doesnt use shaded version of command api.
Even if i added command .withPermission("test") it wouldnt work.

`new CommandAPICommand("test1")
                .executesPlayer((sender, args) -> {
                    sender.sendMessage("test");
                }).register();`

**Comment by JorelAli** [comment]
@Zoltus 
Did you run `CommandAPI.onEnable(plugin)` in your shaded plugin's `onEnable()` method? The `CommandAPI.onEnable(plugin)` method schedules the CommandAPI's permission linker which runs when the server finishes starting up.

**Comment by Zoltus** [comment]
> @Zoltus Did you run `CommandAPI.onEnable(plugin)` in your shaded plugin's `onEnable()` method? The `CommandAPI.onEnable(plugin)` method schedules the CommandAPI's permission linker which runs when the server finishes starting up.
How stupid am I, i literally was missing that.
