### ISSUE TITLE
It always occurs NullpointerException.

### ISSUE THREAD

**Issue by mugchuge** [JorelAli/CommandAPI#248]
**CommandAPI version:** _5.12_

**Minecraft version:** _1.16.5_

**What I did:**

- List of stuff that I did

I applied your library, created a plug-in, and applied it to the server.

**Actual result:**

NullpointerException was
Occurs and commands are not used.

```
Stuff that happened when I did it (post error logs here for example)
```

I tried 32 times but always NullpointerException was Occurs and commands are not used.

**What should have happened:**

- List of things that should happen instead of whatever the bug is

**Comment by JorelAli** [comment]
You haven't provided me with enough information that I can use to help you. It would help if you provided some code that you used, the commands that you tried to run and the console output for the Minecraft server.

**Comment by mugchuge** [comment]
First one like this.
![bu](https://user-images.githubusercontent.com/92763765/142555642-6691290f-25a3-48d8-96a8-289c62326f92.PNG)
is

And my command is "sample", so I input "/sample" but it doesn't work...

**Comment by JorelAli** [comment]
Are you shading the CommandAPI?

**Comment by mugchuge** [comment]
Um...sorry, I can't understand "shading the CommandApi"

**Comment by mugchuge** [comment]
Hello?

**Comment by mugchuge** [comment]
I don't know it.. How can I check it?

**Comment by Minenash** [comment]
Did you run CommandAPI's onLoad method in yours?

**Comment by mugchuge** [comment]
It doesn't work.
![bug](https://user-images.githubusercontent.com/92763765/142564221-53f795e6-ea2d-412d-9c3e-a9766ca37e10.PNG)

I wrote it

@Override
public void onLoad() {
    // I wrote it
}

**Comment by mugchuge** [comment]
Oh! I resolved it. Thank you for helping me.


I will close issue.
