### ISSUE TITLE
Import Annotation bug

### ISSUE THREAD

**Issue by PrismoidNW** [JorelAli/CommandAPI#258]
API Version: 6.4.0

MC Version: 1.18.1

What I did:
- I tried to write the whole argument out, still error
- Tried to write just @A and then see if it pops up in the menu

Result: Gave error
What should have happened: Should not have given an error and able to use it

Pictures: 
![image](https://user-images.githubusercontent.com/75911941/150621987-c4da3299-a820-4f5c-8a5b-87864266db6c.png)
![image](https://user-images.githubusercontent.com/75911941/150621991-d2977f2b-c508-4525-a7e3-bf300b36a433.png)

**Comment by JorelAli** [comment]
CommandAPI version 6.4.0 is not compatible with 1.18.1 - you should be using version 6.5.2 or later.
_(Also, this could be due to a myriad of other dependency-related issues, which you've not provided the information (e.g. `pom.xml` or `build.gradle`) for me to look into)_.
