### ISSUE TITLE
String arguments not picking up special characters

### ISSUE THREAD

**Issue by willkroboth** [JorelAli/CommandAPI#261]
**CommandAPI version:** _6.5.4_

**Minecraft version:** _1.18.2_

**What I did:**

Made a command containing a StringArgument:
```Java
new CommandAPICommand("test")
                .withArguments(new StringArgument("arg"))
                .executes(((sender, objects) -> {
                    sender.sendMessage((String) objects[0]);
                }))
                .register();
```

**Actual result:**

Running the command in the console:
```
> test a
[INFO]: a
> test *
[INFO]: Expected whitespace to end one argument, but found trailing data
[INFO]: test *<--[HERE]
> test /
[INFO]: Expected whitespace to end one argument, but found trailing data
[INFO]: test /<--[HERE]
> test +
[INFO]: +
> test \
[INFO]: Expected whitespace to end one argument, but found trailing data
[INFO]: test \<--[HERE]
> test *e
[INFO]: Expected whitespace to end one argument, but found trailing data
[INFO]: test *e<--[HERE]
> test e*
[INFO]: Expected whitespace to end one argument, but found trailing data
[INFO]: test e*<--[HERE]
> test  *e
[INFO]: Expected whitespace to end one argument, but found trailing data
[INFO]: test *e<--[HERE]
> test  *e

```

**What should have happened:**

When inputting a special character like * \ or /, the command should run like normal, like it did with the a case, instead of creating an error.

**Comment by JorelAli** [comment]
This is "by design" and is working exactly as intended as declared by the documentation for string arguments: https://commandapi.jorel.dev/6.5.4/stringarguments.html#string-argument

> The `StringArgument` class is used to represent a single word. **These words can only contain alphanumeric characters (A-Z, a-z and 0-9), and the underscore character.**

Have you tried using a `TextArgument` or a `GreedyStringArgument` instead?

**Comment by willkroboth** [comment]
Whoops, that's my bad for not reading the documentation closely enough °~°. I suppose this could be changed to a suggestion that the StringArgument should pick up on those special characters. Is there a technical reason that characters like * or / can only be input inside of " " using a TextArgument or with a GreedyString? Considering that CustomArguments are basically StringArguments with a parser in between it could be useful to let those include * and /

**Comment by JorelAli** [comment]
> Is there a technical reason that characters like * or / can only be input inside of " " using a TextArgument or with a GreedyString?

Yes. Strings (StringArgument, TextArgument and GreedyStringArgument) all have the same underlying "argument" implementation, which is the [StringArgumentType](https://github.com/Mojang/brigadier/blob/master/src/main/java/com/mojang/brigadier/arguments/StringArgumentType.java) from the Brigadier library.

Regular strings (StringArgument), also known as unquoted strings are must obey the constraints declared in [`StringReader.isAllowedInUnquotedString`](https://github.com/Mojang/brigadier/blob/master/src/main/java/com/mojang/brigadier/StringReader.java#L169).
Quoted strings (TextArgument) let you use any character as long as it's inside quotes, as specified by [`StringReader.readQuotedString`](https://github.com/Mojang/brigadier/blob/master/src/main/java/com/mojang/brigadier/StringReader.java#L185)
Greedy strings accept anything.

All of this is implemented by Mojang's Brigadier library which the CommandAPI builds off of. These are the limitations that the CommandAPI must adhere to, and by transitivity, the developers that use the CommandAPI.

**Comment by CJCrafter** [comment]
To add, if you only have a few special cases like `*`, consider adding it as a literal argument.
