### ISSUE TITLE
Gradle cannot find annotations dependency

### ISSUE THREAD

**Issue by Lucaskyy** [JorelAli/CommandAPI#276]
Hello. I'm shading CommandAPI inside my plugin and I'd like to use the annotations-based commands.
Gradle is able to find `commandapi-shade`, but it cannot find `commandapi-annotations`.
Weirdly enough, looking at the specified CodeMC Maven repository I cannot find CommandAPI at all.
This is my `build.gradle.kts`:
```kts
plugins {
    kotlin("jvm") version "1.6.21"
    java
    id("com.github.johnrengelman.shadow") version "7.1.2"
}

group = "com.example"
version = "1.0"

repositories {
    mavenCentral()
    maven("https://repo.purpurmc.org/snapshots/")
    maven("https://oss.sonatype.org/content/groups/public/")
    maven("https://repo.codemc.org/repository/maven-public/")
}

dependencies {
    compileOnly("org.purpurmc.purpur", "purpur-api", "1.18.2-R0.1-SNAPSHOT")

    implementation("dev.jorel", "commandapi-shade", "8.0.0")
    compileOnly("dev.jorel", "commandapi-annotations", "8.0.0")
    annotationProcessor("dev.jorel", "commandapi-annotations", "8.0.0")
}
```

**Comment by Lucaskyy** [comment]
I "solved" this for now by getting it from JitPack. But either docs should be updated or this should be fixed, unless I'm doing something wrong myself.

**Comment by JorelAli** [comment]
I don't know what's going on with your setup, but I was able to build a simple project fine without using JitPack.

By searching MavenCentral, I can confirm that the `commandapi-annotations` package does exist:
https://search.maven.org/search?q=dev.jorel

<img width="941" alt="image" src="https://user-images.githubusercontent.com/4613171/166163729-3605d28b-3869-4741-b052-32382b277fe8.png">

**Comment by Lucaskyy** [comment]
I don't know too anymore, it seems to work now. I'm very confused.
