### ISSUE TITLE
CommandAPI prefix appears twice in the console

### ISSUE THREAD

**Issue by DerEchtePilz** [JorelAli/CommandAPI#284]
**CommandAPI version:** _8.1.0_

**Minecraft version:** _1.18.1_

**What I did:**
- Starting my server while using the CommandAPI (shaded)

**Actual result:**

```
[22:10:35 INFO]: [CommandAPI] [CommandAPI] Hooked into Spigot successfully for Chat/ChatComponents
[22:10:35 INFO]: [CommandAPI] [CommandAPI] Hooked into Adventure for AdventureChat/AdventureChatComponents
```
_(I guess it's happening quite a time now but I didn't notice it)_

**What should have happened:**

- The prefix should only appear once instead of appearing twice

**Comment by SNWCreations** [comment]
Uh, Maybe the logger use "Bukkit.getConsoleSender().sendMessage("[CommandAPI] " + message)"?
I think it is not a bug. Because the features can run normally.

**Comment by SNWCreations** [comment]
Uh, Maybe the logger use "Bukkit.getConsoleSender().sendMessage("[CommandAPI] " + message)"?
I think it is not a bug. Because the features can run normally.

**Comment by JorelAli** [comment]
> Uh, Maybe the logger use "Bukkit.getConsoleSender().sendMessage("[CommandAPI] " + message)"? I think it is not a bug. Because the features can run normally.

This is a bug and I specifically requested that someone raised it on GitHub.

**Comment by SNWCreations** [comment]
> 

(NOT USEFUL, SO DON'T READ THIS IF YOU HAVE IMPORTANT THING TO DO)

Hah, because I met this problem before. And NBT API have the same problem.
`[15:23:53] [RFM Update Checker/INFO]: [RunForMoney] [RunForMoney] The version you are using has not been released yet! This may be a test build of the new version?`
This line was copied from my development server log. (Not in console.)

And this..
```
[15:23:43] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_16_R3! Trying to find NMS support
[15:23:43] [Server thread/INFO]: [NBTAPI] [NBTAPI] NMS support 'MC1_16_R3' loaded!
[15:23:43] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
```
The same problem.

**Comment by SNWCreations** [comment]
Is it fixed? :)
