### ISSUE TITLE
TimeArgument gives unexpected error

### ISSUE THREAD

**Issue by Mullp** [JorelAli/CommandAPI#314]
### CommandAPI version

8.5.0

### Minecraft version

1.19

### Are you shading the CommandAPI?

Yes

### What I did

- I registered this code in my onLoad() function:
```java
new CommandAPICommand("timeargument")
        .withArguments(new TimeArgument("duration"))
        .executes((commandSender, objects) -> {
          commandSender.sendMessage("Duration: " + (int) objects[0]);
        })
        .register();
```
- I ran "/timeargument 1d"

### What actually happened

I get the error `An unexpected error occurred trying to execute that command` (`Argument 'duration' is defined as , not class java.lang.Integer`)
![image](https://user-images.githubusercontent.com/82767727/182416941-0f856a02-c95e-4cc5-80a1-357852aa53dd.png)

### What should have happened

I would have gotten the message: "Duration: 24000"

**Comment by JorelAli** [comment]
Fixed in 8.5.1.
