### ISSUE TITLE
Custom arguments with suggestions breaks all other suggestions along the same command path

### ISSUE THREAD

**Issue by JorelAli** [JorelAli/CommandAPI#317]
### CommandAPI version

8.5.0

### Minecraft version

1.19

### Are you shading the CommandAPI?

No

### What I did

- Register the following commands:
  ```java
  new CommandAPICommand("sug")
	  .withArguments(new StringArgument("my_str_arg")
		  .includeSuggestions(ArgumentSuggestions.strings("hello", "world")))
	  .executes((sender, args) -> {
		  Bukkit.broadcastMessage("Test");
	  })
	  .register();
  
  new CommandAPICommand("sug")
	  .withArguments(new LocationArgument("my_loc_arg"))
	  .executes((sender, args) -> {
		  Bukkit.broadcastMessage("Test");
	  })
	  .register();
  
  Argument<String> myCustArg = new CustomArgument<>(
	  new StringArgument("my_cust_arg"), info -> {
		  return "cust_arg_result";
	  })
	  .includeSuggestions(ArgumentSuggestions.strings(info -> {
		  return new String[] {"goodbye", "moon"};
	  }));
  
  new CommandAPICommand("sug")
	  .withArguments(myCustArg)
	  .executes((sender, args) -> {
		  Bukkit.broadcastMessage("Test");
	  })
	  .register();
  ```
- Type `/sug ` in-game

### What actually happened

No suggestions are displayed

### What should have happened

The following suggestions should be displayed:
- hello
- world
- goodbye
- moon
- ~
- ~ ~
- ~ ~ ~

### Other

If you register the first two commands (with my_str_arg and my_loc_arg), suggestions work as intended. The introduction of the custom argument breaks all existing suggestions for some reason.

**Comment by willkroboth** [comment]
This is not just a problem with `CustomArgument`. For example, this code triggers the issue:
```java
new CommandAPICommand("sug")
        .withArguments(new IntegerArgument("int")
                .replaceSafeSuggestions(SafeSuggestions.suggest(1, 2))
        )
        .executes((sender, args) -> {
            Bukkit.broadcastMessage("Test");
        })
        .register();

new CommandAPICommand("sug")
        .withArguments(new PlayerArgument("player")
                .replaceSafeSuggestions(SafeSuggestions.suggestCollection(info -> (List<Player>) Bukkit.getOnlinePlayers()))
        )
        .executes((sender, args) -> {
            Bukkit.broadcastMessage("Test");
        })
        .register();
```
The root cause is a Vanilla client issue documented here: https://bugs.mojang.com/browse/MC-261429. This issues happens when sibiling nodes in the Brigadier CommandDispatcher tree both need to ask the server for suggestions. The Vanilla client dose not handle the situation correctly, and doesn't show any suggestions. Note that the console displays suggestions correctly since it doesn't have this issue.

**Comment by JorelAli** [comment]
Marking as won't fix. This is a Vanilla client bug and isn't something that the CommandAPI is capable of resolving. I think our dedicated solution is simply to avoid designing commands which can have conflicting suggestions. This can be done by adding intermediary `LiteralArgument` nodes, for example:

Instead of writing a command like this:
```java
/sug -> my_str_arg
/sug -> my_loc_arg
/sug -> my_cust_arg
```
Consider writing the command like this:
```java
/sug -> string -> my_str_arg
/sug -> location -> my_loc_arg
/sug -> cust -> my_cust_arg
```
