### ISSUE TITLE
A way to split subcommands into their own classes for the annotations API

### ISSUE THREAD

**Issue by blubbarbs** [JorelAli/CommandAPI#318]
### Description

Currently (in the dev branch), subcommands are nested within the parent Command class. For example, take [this test command](https://github.com/JorelAli/CommandAPI/blob/dev/annotations/commandapi-annotations/src/test/java/dev/jorel/commandapi/test/MyCommand.java) from the dev-annotations branch: 

```java
@Command("mycommand")
public class MyCommand {

	@Subcommand("hi")
	public class Hi {

		@Subcommand
		public void hi(CommandSender sender) {
			System.out.println("Hi");
		}
	}

	// TODO: This should be a valid case which does the same thing as the thing
	// above it
//	@Subcommand("hi")
//	public void hi(CommandSender sender) {
//		System.out.println("Hi");
//	}

	@Subcommand("nested")
	public class Nested {

		@Subcommand
		public void toPlayer(CommandSender sender, @APlayerArgument Player player) {
			System.out.println("Hi " + player.getName());
		}

		@Subcommand("hello")
		public class Hello {

			@Subcommand
			public void hello(CommandSender sender) {
				System.out.println("Hello");
			}
		}
	}
}
```

I feel like this approach of infinitely nested subcommand classes could become messy extremely quickly, especially as more commands get added. My idea would be to implement some sort of command-pathing system within the command class declaration. This could be done within the initial "Subcommand" annotation or with a new annotation, "@CommandPath".

### Expected code

For example, the "nested" subcommand above could be split into a new class like this:

```java
	@Subcommand("mycommand.nested")
	public class Nested {

		@Subcommand
		public void toPlayer(CommandSender sender, @APlayerArgument Player player) {
			System.out.println("Hi " + player.getName());
		}

		@Subcommand("hello")
		public class Hello {

			@Subcommand
			public void hello(CommandSender sender) {
				System.out.println("Hello");
			}
		}
	}
```

Or this, using the hypothetical @CommandPath annotation: 

```java
        @CommandPath("mycommand")
	@Subcommand("nested")
	public class Nested {

		@Subcommand
		public void toPlayer(CommandSender sender, @APlayerArgument Player player) {
			System.out.println("Hi " + player.getName());
		}

		@Subcommand("hello")
		public class Hello {

			@Subcommand
			public void hello(CommandSender sender) {
				System.out.println("Hello");
			}
		}
	}
```

### Extra details

A final thing I'm wondering about is why there is a @Subcommand annotation at all. In the core API, the subcommands that are registered are normal CommandAPICommand objects, so I'm wondering if it'd make more sense to just merge the @Command and @Subcommand annotations. 

EDIT: I just looked at the source code, and it seems that the @Alias annotation has been removed in lieu of potential aliases in the @Command or @Subcommand declaration. For this suggestion to work, commands and subcommands have to have a canonical name, so I think that @Alias annotation should return with only the canonical command name being declared in the initial command/subcommand annotations.

**Comment by JorelAli** [comment]
This suggestion doesn't address arguments declared between commands and subcommands. In the new annotation API, it will be possible to declare a command of the form `/command <argument> subcommand ...`

I'm wondering if simply using an external class and inheritance may be better. Perhaps something like

```java
@Command("mycommand")
public class MyCommand {

  @AIntegerArgument
  public int someArgument;

  @Subcommand(SomeSubcommand.class)
  public SomeSubcommand subcommand;

}
```

```java
@Subcommand("blah")
public class SomeSubcommand extends MyCommand{

  ...

}
```

This way, it would be possible to access the fields of the parent command class, while also keeping the subcommand class in a file of its own.

I agree with the `@Command` vs `@Subcommand` point - they may as well be the same - there's effectively no difference between the two as far as I'm aware. It's possible that the alias annotation could return, or added as an extra parameter to the `@Command` annotation, such as `@Command(name = "", aliases = { ... })`

**Comment by blubbarbs** [comment]
I can agree with the inheritance suggestion, I wasn't thinking about the argument -> subcommand order. Personally, adding the aliases as an extra parameter to the annotation seems cleaner to me than the `@Alias` annotation, so I think you should go with that.
