### ISSUE TITLE
Some Class files not included while shading

### ISSUE THREAD

**Issue by matrixidot** [JorelAli/CommandAPI#327]
### CommandAPI version

8.5.1

### Minecraft version

1.19

### Are you shading the CommandAPI?

Yes

### What I did

- In my Pom.xml I added the shade plugin and the commandapi-shade as stated in the documentation for CommandAPI8.5.1
- I refreshed and Invalidated caches in maven and Intellij
- I used mvn clean package to build the jar

### What actually happened

- Everything worked as intended but when I decompiled the Jar I noticed that PlayerArgument.class and SafeOverrideableArgument.class was missing among others.

### What should have happened

- All the files from CommandAPI should have been shaded into my final jar

### Server logs and CommandAPI config

- N/A

### Other

It was working up untill a point when it started to just not include those classes
They are the same classes each time not random

**Comment by JorelAli** [comment]
Without your pom.xml file, there's basically nothing I can do.

Are you using Jar minimisation?

**Comment by matrixidot** [comment]
Here is the pom, and yes
https://github.com/matrixidot/TwistAPI/blob/master/pom.xml

**Comment by matrixidot** [comment]
Closing issue because I solved it. Issue was Jar minimization.
