### ISSUE TITLE
Chat Component support in command execution fail

### ISSUE THREAD

**Issue by MichixYT** [JorelAli/CommandAPI#334]
### Description

I'd like if the CommandAPI would let you use chat components in `CommandAPI::fail` method

### Expected code

For example, `CommandAPI.fail(BaseComponent... component)`

**Comment by JorelAli** [comment]
Implemented in #322 and made available in the latest 8.6.0-SNAPSHOT build.

**Comment by JorelAli** [comment]
Implemented in release [8.6.0](https://github.com/JorelAli/CommandAPI/releases/tag/8.6.0).
