### ISSUE TITLE
TextArgument backed ListArgument 

### ISSUE THREAD

**Issue by Minenash** [JorelAli/CommandAPI#351]
### Description

Currently, the ListArgument uses GreedyStringArgument as the backbone, and while it has the advantage of not needing quotes for anything not alphanumeric_, it limits commands to a maximum of 1 list arguments.

It would be nice to also have a TextArgument backed version, that would allow multiple lists, with the cost of quotes, unless they use _ as the delimiter.

### Expected code

The simplest would probably be changing the `.build()` to `.buildGreedy()` an ` .buildText()`, with `.build()` being an alias to the greedy one to keep compatibility

**Comment by JorelAli** [comment]
Implemented for 8.6.0's release.

**Comment by JorelAli** [comment]
Implemented in release [8.6.0](https://github.com/JorelAli/CommandAPI/releases/tag/8.6.0).
