### ISSUE TITLE
Add miscellaneous argument type 'World'

### ISSUE THREAD

**Issue by lokka30** [JorelAli/CommandAPI#358]
### Description

Allows us to select world names, such as:

- `/kill @e[type=creeper] my_cool_world`

..where `my_cool_world` is a world loaded on the server.

Can also be used as a list:

- `/kill @e[type=creeper] my_cool_world world world_nether world_the_end resource_world`

**Comment by lokka30** [comment]
Unfortunately the current workaround doesn't seem to work on `load: STARTUP` plugins, nor on worlds which have been loaded after the plugin's commands were registered.
I have tried a workaround where I have replaced the suggestions with a list of worlds which are queried async, of course this hasn't resolved the issue since the list of allowed list values have not been modified.
For now, I will make it use a string list argument and parse worlds manually. 🙂

**Comment by lokka30** [comment]
Thanks, no worries :)

**Comment by JorelAli** [comment]
After a quick chat with a member from the CommandAPI Discord server, I've discovered that the CommandAPI's implementation of Minecraft's `DimensionArgument` is terrible and doesn't do what it is supposed to!

Scheduling the implementation of a `DimensionArgument` for CommandAPI 8.6.0 which will do pretty much exactly what you would expect - it returns a Bukkit `World` object.

**Comment by JorelAli** [comment]
Implemented in release [8.6.0](https://github.com/JorelAli/CommandAPI/releases/tag/8.6.0).
