### ISSUE TITLE
Change default short description of CommandAPI commands

### ISSUE THREAD

**Issue by DerEchtePilz** [JorelAli/CommandAPI#371]
### Description

So, currently when creating a command without explicitly specifying a description for the command, the CommandAPI just sets:
`A Mojang provided command.`
This is stated in [CommandAPIBukkit#updateHelpForCommands](https://github.com/JorelAli/CommandAPI/blob/master/commandapi-platforms/commandapi-bukkit/commandapi-bukkit-core/src/main/java/dev/jorel/commandapi/CommandAPIBukkit.java#L302)

My suggestion is to change that text to be something along the lines of:
`A CommandAPI provided command.` as the command obviously isn't added by Minecraft.

**Comment by JorelAli** [comment]
Implemented in 9.0.2
