### ISSUE TITLE
Argument for player name

### ISSUE THREAD

**Issue by demkom58** [JorelAli/CommandAPI#405]
### Description

There are already arguments that allow you to get the player, for example `OfflinePlayerArgument` and `PlayerArgument`, but we don’t always need an offline player object right away (loading an offline player can sometimes have a big impact on performance) or an online player.

It would be nice to add a new argument, `PlayerNameArgument`, which would suggest online players names but also allow any other names to be specified.

### Expected code

```Java
        new CommandAPICommand("warn")
                .withPermission("my.super.cool.perm")
                .withArguments(new PlayerNameArgument("player", /* regex validation */ true))
                .withArguments(new GreedyStringArgument("reason"))
                .executes(new WarnCommandExecutor(...), ExecutorType.CONSOLE, ExecutorType.PLAYER)
                .register();
```

**Comment by DerEchtePilz** [comment]
I don’t understand why you would need to specify a different value as a player name.
If you want to warn a player you would use a player name.
Why would you want different names?

**Comment by willkroboth** [comment]
From what you posted, I think you can create an argument that does what you want with something like this:
```java
new CommandAPICommand("warn")
        .withPermission("my.super.cool.perm")
        .withArguments(
                new StringArgument("player").replaceSuggestions(ArgumentSuggestions.strings(
                        info -> Bukkit.getOnlinePlayers().stream().map(Player::getName).toArray(String[]::new)
                )),
                new GreedyStringArgument("reason")
        )
        .executes((sender, args) -> {
            String playerName = (String) args[0];

            // Check player name
            if(!playerName.matches("coolRegexExpression")) throw CommandAPI.failWithString("Player name is invalid");

            // Get player
            Player player = Bukkit.getPlayer(playerName);
        }, ExecutorType.CONSOLE, ExecutorType.PLAYER)
        .register();
```
You can use a StringArgument to accept any String, but also make it suggest the names of online players using `replaceSuggestions` (see the [documentation](https://commandapi.jorel.dev/8.7.0/argumentsuggestions.html) for more on how that works).

I saw "regex validation" in your comment, so I added a regex check into the executes method. If that check fails, you can make your command fail with `CommandAPI#failWith...` (See [Handling command failure](https://commandapi.jorel.dev/8.7.0/commandfailures.html)). If the name is okay, then you can convert the name into a Player.

If you will use an argument like this multiple times, you can create a CustomArgument, something like this:
```java
public class PlayerNameArgument extends CustomArgument<Player, String> {
    public PlayerNameArgument(String nodeName, String regex) {
        this(nodeName, Pattern.compile(regex));
    }

    private PlayerNameArgument(String nodeName, Pattern regex) {
        super(new StringArgument(nodeName), customArgumentInfo -> {
            String playerName = customArgumentInfo.currentInput();

            if(!regex.matcher(playerName).matches()) throw new CustomArgumentException("Player name is invalid!");

            return Bukkit.getPlayer(playerName);
        });
        replaceSuggestions(ArgumentSuggestions.strings(
                info -> Bukkit.getOnlinePlayers().stream().map(Player::getName).toArray(String[]::new)
        ));
    }
}
```
This custom argument will handle checking the player name against a regex, throwing a command exception if it doesn't work, then converting the name to a Player. The suggestions will also be automatically set up to suggest the online player names. You can read more about CustomArgument [here](https://commandapi.jorel.dev/8.7.0/customarguments.html).

Does that work for you?

**Comment by demkom58** [comment]
> I don’t understand why you would need to specify a different value as a player name. If you want to warn a player you would use a player name. Why would you want different names?

When I wrote this, I had in mind the names of offline players.

**Comment by demkom58** [comment]
> From what you posted, I think you can create an argument that does what you want with something like this:
> 
> ```java
> new CommandAPICommand("warn")
>         .withPermission("my.super.cool.perm")
>         .withArguments(
>                 new StringArgument("player").replaceSuggestions(ArgumentSuggestions.strings(
>                         info -> Bukkit.getOnlinePlayers().stream().map(Player::getName).toArray(String[]::new)
>                 )),
>                 new GreedyStringArgument("reason")
>         )
>         .executes((sender, args) -> {
>             String playerName = (String) args[0];
> 
>             // Check player name
>             if(!playerName.matches("coolRegexExpression")) throw CommandAPI.failWithString("Player name is invalid");
> 
>             // Get player
>             Player player = Bukkit.getPlayer(playerName);
>         }, ExecutorType.CONSOLE, ExecutorType.PLAYER)
>         .register();
> ```
> 
> You can use a StringArgument to accept any String, but also make it suggest the names of online players using `replaceSuggestions` (see the [documentation](https://commandapi.jorel.dev/8.7.0/argumentsuggestions.html) for more on how that works).
> 
> I saw "regex validation" in your comment, so I added a regex check into the executes method. If that check fails, you can make your command fail with `CommandAPI#failWith...` (See [Handling command failure](https://commandapi.jorel.dev/8.7.0/commandfailures.html)). If the name is okay, then you can convert the name into a Player.
> 
> If you will use an argument like this multiple times, you can create a CustomArgument, something like this:
> 
> ```java
> public class PlayerNameArgument extends CustomArgument<Player, String> {
>     public PlayerNameArgument(String nodeName, String regex) {
>         this(nodeName, Pattern.compile(regex));
>     }
> 
>     private PlayerNameArgument(String nodeName, Pattern regex) {
>         super(new StringArgument(nodeName), customArgumentInfo -> {
>             String playerName = customArgumentInfo.currentInput();
> 
>             if(!regex.matcher(playerName).matches()) throw new CustomArgumentException("Player name is invalid!");
> 
>             return Bukkit.getPlayer(playerName);
>         });
>         replaceSuggestions(ArgumentSuggestions.strings(
>                 info -> Bukkit.getOnlinePlayers().stream().map(Player::getName).toArray(String[]::new)
>         ));
>     }
> }
> ```
> 
> This custom argument will handle checking the player name against a regex, throwing a command exception if it doesn't work, then converting the name to a Player. The suggestions will also be automatically set up to suggest the online player names. You can read more about CustomArgument [here](https://commandapi.jorel.dev/8.7.0/customarguments.html).
> 
> Does that work for you?

Thank you, looks like what I need. Anyway, this is kind of a commonly used argument, it would be cool to see it built into the framework.

**Comment by DerEchtePilz** [comment]
I think (but I am not sure) that this is not a argument that will be implemented.
Here are a few reasons for that:
- It can be implemented using the CustomArgument
- It doesn’t use a NMS implementation

I don’t know the exact reasons but if I find the PR where I tried to implement a WorldArgument without NMS it got denied. If I find that PR I will post the link to the comment right here.

**Comment by DerEchtePilz** [comment]
Alright [here](https://github.com/JorelAli/CommandAPI/pull/365#issuecomment-1324889999) you can find the response I was referring to.
