### ISSUE TITLE
LiteralArgument classes should get a node name so they can be referenced by node name in the executor

### ISSUE THREAD

**Issue by DerEchtePilz** [JorelAli/CommandAPI#448]
### Description

As of CommandAPI 9.0.0, arguments are no longer stored in an array that is accessed directly but instead a `CommandArguments` class has been introduced to provide a more powerful way of dealing with arguments.

This includes being able to get an argument by its node name via the method `CommandArguments#get(String)`.

However, this is not possible for the `MultiLiteralArgument` and the `LiteralArgument` because they only accept values to be shown to the player.

I personally don't know if this is even possible but that would be very useful.

### Extra details

Raised because of messages in the CommandAPI discord:
[1. Message](https://discord.com/channels/745416925924032523/745757702608912556/1099608113130258493)
[2. Message](https://discord.com/channels/745416925924032523/745757702608912556/1108173187331674212)

**Comment by JorelAli** [comment]
Implemented in 9.0.2.
