### ISSUE TITLE
Tooltips for LiteralArguments

### ISSUE THREAD

**Issue by tinyoverflow** [JorelAli/CommandAPI#475]
### Description

It would be awesome if LiteralArguments would support tooltips, so when the user hovers over the suggestion for that LiteralArgument, he get's a tooltip.

### Expected code

I think something like the following would be great:

```java
new LiteralArgument("field")
    .withTooltip(Component/String)
    // ...
```

**Comment by JorelAli** [comment]
Can't fix, because this is a Brigadier limitation. This is something described in more detail in the [documentation's FAQ page](https://commandapi.jorel.dev/9.0.3/faq.html#can-you-add-tooltips-to-literalmultiliteral-arguments)
