### ISSUE TITLE
How to make ignore-case-sensitive command?

### ISSUE THREAD

**Issue by lastsurvivors** [JorelAli/CommandAPI#518]
### Description

How to make ignore-case-sensitive command?
i'm using CommandAPI 9.3.0 on 1.20.4

### Extra details

new CommandAPICommand("hello")
                .executesPlayer((sender, args) -> {
                    sender.damage(20);
                }).register();
                
/hello (working)
/HELLO (not-working)

**Comment by DerEchtePilz** [comment]
I think I am going to close this issue now. If you've got any further questions, feel free to join the discord server or open another issue if you run into any issues.
