### ISSUE TITLE
Help generation doesn't work for the namespaced version of a command

### ISSUE THREAD

**Issue by DerEchtePilz** [JorelAli/CommandAPI#538]
### CommandAPI version

9.4.0-SNAPSHOT

### Minecraft version

1.20.4

### Are you shading the CommandAPI?

Yes

### What I did

I encountered this bug while testing the fix for #536 . I have my `CommandAPIBukkitConfig` set up as follows:
```java
CommandAPI.onLoad(new CommandAPIBukkitConfig(this)
    .missingExecutorImplementationMessage("You cannot execute this command!")
    .dispatcherFile(new File(getDataFolder(), "command_registration.json"))
    .usePluginNamespace()
);
```

I then registered this command:
```kt
commandAPICommand("test") {
    multiLiteralArgument(nodeName = "type", "java", "bedrock")
    stringArgument("additional")
    playerExecutor { player, args ->
        val type: String by args
        player.sendMessage(Component.text().content(type))
    }
}
```

### What actually happened

I believe this screenshot shows it best:
![image](https://github.com/JorelAli/CommandAPI/assets/81232921/3395adcf-860e-4525-9e22-5497927b3c7f)

### What should have happened

The help menus should be identical.

### Other

This issue most likely isn't applicable to the latest snapshot version only. I believe it definitely happened before too.

**Comment by JorelAli** [comment]
Fixed in version 9.4.0.
