### ISSUE TITLE
Update to 1.20.5

### ISSUE THREAD

**Issue by mrjasonn** [JorelAli/CommandAPI#548]
### Description

Please do would be very useful as there are other plugins waiting on you to update

**Comment by JorelAli** [comment]
We're still ploughing through our 1.20.5 release procedures. At the time of writing, we have:
- 2 pull requests that need finishing up
- Documentation to generate
- JavaDocs to produce
- Manual testing to perform
- Changelogs to update

Our deadline for 1.20.5 support is 30th April - we should have a release by then.

**Comment by JorelAli** [comment]
Implemented in version 9.4.0.
