### ISSUE TITLE
The documentation should update its instructions for Gradle shadow for Java 21

### ISSUE THREAD

**Issue by JorelAli** [JorelAli/CommandAPI#567]
### Documentation URL

https://commandapi.jorel.dev/9.5.0/setup_shading.html#shading-with-gradle

### What the documentation currently says

The documentation declares this:
```groovy
plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}
```

This is incompatible with Java 21

### Proposed fix

We should look at pointing to the [Goooler shadow fork](https://plugins.gradle.org/plugin/io.github.goooler.shadow)
```java
  id 'java'
  id 'io.github.goooler.shadow' version '8.1.7'
```

**Comment by DerEchtePilz** [comment]
Implemented in version 9.5.2
