### ISSUE TITLE
ArgumentSuggestions missing stringCollectionAsync & stringCollection in Wiki

### ISSUE THREAD

**Issue by lowercasebtw** [JorelAli/CommandAPI#574]
### Documentation URL

https://commandapi.jorel.dev/9.5.0/argumentsuggestions.html#the-argumentsuggestions-interface

### What the documentation currently says

![image](https://github.com/JorelAli/CommandAPI/assets/126462578/b19fc1f9-1e5f-42e5-95ea-76caf569a9ba)

### Proposed fix

add
ArgumentSuggestions stringCollection(Collection<String> collection);
ArgumentSuggestions stringCollectionAsync(Collection<String> collection);

**Comment by JorelAli** [comment]
Thanks for letting us now about this!
Implemented for the next release. This change can be viewed on the live documentation [here](https://commandapi-live-docs.jorel.dev/argumentsuggestions.html#the-argumentsuggestions-interface):

![image](https://github.com/JorelAli/CommandAPI/assets/4613171/2811e328-2332-4f2b-8f0c-a01195bbff05)

**Comment by lowercasebtw** [comment]
:)
