### ISSUE TITLE
Error when registering datapacks

### ISSUE THREAD

**Issue by RivoDani** [JorelAli/CommandAPI#582]
### CommandAPI version

9.5.1

### Minecraft version

1.20.5

### Are you shading the CommandAPI?

No

### What I did

I just ran the server with some of the vanilla tweaks datapacks

### What actually happened

An error occured, and command completion didn't work anymore.

### What should have happened

Everything should load just fine.

### Server logs and CommandAPI config

[latest.log](https://github.com/user-attachments/files/16363749/latest.log)
[config.txt](https://github.com/user-attachments/files/16363756/config.txt)
(config is in .txt because github doesn't accept .yml)

**Comment by willkroboth** [comment]
I put the uploaded files in an online paste for easier viewing: https://paste.gg/p/anonymous/a0a6cd6973ee477891588a0e1741adb2. This looks like the problem solved by https://github.com/JorelAli/CommandAPI/pull/580. Try using the CommandAPI plugin jar for that PR: https://github.com/JorelAli/CommandAPI/actions/runs/10033211364?pr=580#:~:text=Size-,CommandAPI%20(Bukkit%20plugin),-672%20KB.

**Comment by RivoDani** [comment]
It seems that really solved the problem, should this issue be closed now or when the 9.6.0 update releases?

**Comment by willkroboth** [comment]
I think we typically close issues once we release the update that resolves them, so we can keep this open for now :+1: (#580 also isn't merged into `dev/dev`, so the fix isn't even available in `9.6.0-SNAPSHOT` yet :P).

**Comment by willkroboth** [comment]
Should be fixed since version 9.5.2
